<script type="text/javascript">
    var social_interaction_track_fb_like = <?php print $this->getDataSetDefault('fb_like', 0); ?>;
    var social_interaction_track_fb_unlike = <?php print $this->getDataSetDefault('fb_unlike', 0); ?>;
    var social_interaction_track_fb_share = <?php print $this->getDataSetDefault('fb_share', 0); ?>;
    var social_interaction_track_twitter_interactions = <?php print $this->getDataSetDefault('twitter_interactions', 0); ?>;
</script>