<script type="text/javascript">
    var social_interaction_track_fb_like = <?php print $this->getData('fb_like'); ?>;
    var social_interaction_track_fb_unlike = <?php print $this->getData('fb_unlike'); ?>;
    var social_interaction_track_fb_share = <?php print $this->getData('fb_share'); ?>;
    var social_interaction_track_twitter_interactions = <?php print $this->getData('twitter_interactions'); ?>;
</script>