<?php
/**
 * Atwix
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 * @category    Atwix
 * @package     Atwix_UniversalAnalytics
 * @author      Atwix Core Team
 * @copyright   Copyright (c) 2012 Atwix (http://www.atwix.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @var $this Interactiv4_GAConversionTrack_Block_Ua
 */
?>
<?php $accountId = Mage::helper('i4gaconversiontrack')->getAccount(); ?>
<?php if ($accountId):?>
<!-- BEGIN GOOGLE UNIVERSAL ANALYTICS CODEs -->
<script type="text/javascript">
//<![CDATA[
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function()
    { (i[r].q=i[r].q||[]).push(arguments)}
        ,i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','__gaTracker');

    __gaTracker('create', '<?php echo $accountId ?>', <?php echo $this->getAccountParams() ?>);
    __gaTracker('send', 'pageview');
    <?php echo $this->_getOrdersTrackingCode() ?>

//]]>
</script>
<!-- END GOOGLE UNIVERSAL ANALYTICS CODEs -->
<?php endif; ?>
